services:


  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: learnphp
    ports:
    - 3306:3306
    volumes:
      - ta24adbdata:/var/lib/mysql


volumes:
  ta24adbdata: